# Videos y Diapositivas {.unnumbered}

La parte teórica de la materia incluye ver los videos y leer los apuntes que se encuentran en esta página. Los apuntes contienen información que se tendrá en cuenta al momento de evaluar la materia en los parciales.

Las clases teóricas son virtuales y asincrónicas. Los videos se encuentran en el <a href="https://www.youtube.com/@pensamientocomputacional-fiuba/playlists" target="_blank"> canal de Youtube</a> de la materia, cada uno con su lista de reproducción correspondiente.


Las clases prácticas son presenciales. Las diapositivas usadas en la práctica se encuentran en <a href="https://drive.google.com/drive/folders/1jEqxJLcCdY9n79nHLWkjaZIlO4bH4tG9?usp=sharing" target="_blank">siguiente link</a> y están organizadas por curso.


## Taller de Herramientas
La materia cuenta con un "Taller de Herramientas" en el <a href="https://www.youtube.com/@pensamientocomputacional-fiuba/playlists" target="_blank"> canal de Youtube</a>.

En esta lista de videos, se explica cómo utilizar las herramientas de la materia como Discord, la página oficial y Google Colab.