## Guía 2: Tipos de Datos, Expresiones y Funciones

1. Guardar el texto "Hola, Mundo!" en una variable e imprimirla por pantalla.

2. Guardar los números 1, 2 y 3 en tres variables distintas e imprimirlos por pantalla.

3. a. Guardar los números 1, 2 y 3 en tres variables distintas y luego sumarlos e imprimir el resultado por pantalla.\
    b. Repetir con las distintas operaciones disponibles que se vieron en la unidad 2: resta, multiplicación, división, división entera, resto, potencia; combinando los números entre sí.

4. Crear un programa que le solicite al usuario:
    a. Su nombre y lo imprima por pantalla.
    b. Su edad y la imprima por pantalla.
    c. Su edad, le sume 1, y la imprima por pantalla.

5. Crear un programa que le solicite al usuario un número, y que imprima el resto obtenido de dividirlo por 2.\
¿Qué operador vimos para obtener el resto?

6. Escribir un programa que le pida al usuario su año de nacimiento, y que le diga qué edad tiene en el año actual.

7. Crear un programa que le solicite al usuario 5 enteros y que muestre por pantalla el promedio de ellos. Hacerlo de dos formas:
    a. Primero, usando 5 variables para cada entero.
    b. Después, usando una sola variable para almacenar la suma de los 5 enteros. ¿Cómo se te ocurre que podrías hacer?

:::{.callout-info}
A partir de ahora y en adelante, todo lo que se nos pida (incluso si dice "programa") se debe realizar dentro de una o más funciones.
:::

8. Crear una **función** que reciba un número y que devuelva el valor absoluto.

9. Crear una **función** que reciba un número y que devuelva `True` si es par, y `False` si es impar.

10. Crear una **función** que reciba un número y un string, y que devuelva ambos concatenados dentro de un nuevo string.

11. Crear una **función** que reciba dos enteros y que devuelva el resto y el cociente entre ellos.

12. Crear una **función** que le pida al usuario su nombre y apellido, e los imprima con el siguiente formato: "Apellido, Nombre".

13. Hacer una **función** que reciba una palabra y devuelva la cantidad de letras que tiene.

14. a. Hacer una **función** que reciba una palabra y que imprima los primeros 5 caracteres únicamente. Ejemplo: Si se recibe "pensamiento" se debe imprimir "pensa".
    b. Hacer una **función** que reciba una palabra y que imprima sólo los caracteres ubicados en posiciones pares. Ejemplo: Si se recibe "pensamiento" se debe imprimir "pnaino".
    c. Hacer una **función** que reciba una palabra y que imprima la palabra dada vuelta. Ejemplo: Si se recibe "materia" se debe imprimir "airetam".

15. Hacer una **funcion** que reciba una palabra, le borre todas las letras "a" e imprima el resultado por pantalla. Pista: usar una función predefinida de Python. Ejemplo: Si se recibe "casa" se debe imprimir "cs".

16. Analizar qué tipo de dato (o error) se obtiene al hacer las siguientes operaciones:
    a. `5 / 2`
    b. `5 // 2`
    c. `5 % 2`
    d. `5 ** 2`
    e. `5.0 / 2`
    f. `5.0 // 2`
    g. `5.0 % 2`
    h. `5.0 ** 2`
    i. `5 / 2.0`
    j. `5 // 2.0`
    k. `5 % 2.0`
    l. `5 ** 2.0`
    m. `5.0 / 2.0`
    n. `5.0 // 2.0`
    o. `5.0 % 2.0`
    p. `5.0 ** 2.0`
    r. `"Hola" * 2`
    r. `"Hola" + 2`
    s. `"Hola" + "2"`
    t. `x = "Hola"`\
       `x += " mundo"`

17. a. Escribir una función que convierta un valor dado en grado Celsius, a Fahrenheit. Recordar que la fórmula para la conversión es: `F = 9/5 * C + 32`.
    b. Escribir una función que convierta un valor dado en grados Fahrenheit, a Celsius. Usar la misma fórmula anterior.

18. Escribir una función que calcule el área de un triángulo recibiendo como parámetros su base y su altura.

19. Siendo el cálculo de la norma de un vector $v$ en $R^3$:\
    $$||v|| = \sqrt{v_1^2 + v_2^2 + v_3^2}$$\
    Escribir una función que calcule la norma de un vector en R3 recibiendo como parámetros las 3 componentes $v_1$, $v_2$ y $v_3$ del mismo.

20. **Desafío** (no obligatorio): Calcular el área de un rectángulo (alineado con los ejes $x$ e $y$), dadas sus coordenadas $x_1$, $x_2$, $y_1$ e $y_2$. Nota: considerar que tiene que funcionar para cualquier cuadrado, independientemente de los cuadrantes en los que tenga sus vértices.
